name: Makefile CI

on:
  push:
    branches: [ "X4000-user-12-SKQ1.231214.001-X4000_X112_240621_ROW-release-keys" ]
  pull_request:
    branches: [ "X4000-user-12-SKQ1.231214.001-X4000_X112_240621_ROW-release-keys" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
